### ISSUE TITLE
Automate this whole guide for Debian/ Ubuntu 64-bit

### ISSUE THREAD

**Issue by durbanpoison** [durbanpoison/zcash-tor#5]
The desired user experience is:

The user should be able to run one command that will automatically download and install Tor (if it is not already installed), run Tor, download and install zcashd and the parameters over Tor, and run and update zcashd over Tor. The user should be able to easily check and make sure that everything is working properly (Zcash is running  and updating exclusively over Tor as expected. The user's IP address should not be exposed to any services connected to Zcash).

The main guide in the readme can be used as a blueprint for what the script (or whatever solution to this issue) will do.

**BOUNTY**
I am offering 0.2 ZEC to the first person who can provide a working solution to this issue. Bounties will only be paid out to z-addresses.

**Comment by chaserileyroberts** [comment]
I was the person who brought this up on twitter so I'll work on this. Plus I have some free time today. 

https://twitter.com/TheNerdStation/status/997557676468047874

**Comment by durbanpoison** [comment]
Small world! Thanks @Thenerdstation.

**Comment by chaserileyroberts** [comment]
Done.

Made an install script and a zcashd-tor script. As far as I can tell, these scripts never touch a zcash service without going through tor. 


https://github.com/durbanpoison/zcash-tor/pull/8

**Comment by durbanpoison** [comment]
I do not code so can only partially discern what the script is doing. I have left a few comments and will also ask for another set of eyes to review before approving and merging the PR.
