### ISSUE TITLE
Maxconnections never reach over 8 peers

### ISSUE THREAD

**Issue by durbanpoison** [durbanpoison/zcash-tor#9]
Modified maxconnections in the Zcash configuration file to be 100. During testing it never got above 8 connections. Figure out why this is the case and fix it if possible.

**Comment by durbanpoison** [comment]
This may be because the node is only a "listening" node. I believe the number of peers only goes over 8 if the node is reachable and uploading data back to the network.

**Comment by rex4539** [comment]
It is hardcoded.

https://github.com/zcash/zcash/blob/c2fa70ddfd7711d514a701b3a7c8adb561acc3ff/net.cpp#L7
https://github.com/zcash/zcash/blob/64f9370691007410d45d1a5af624edfb0291224c/net.cpp#L885

**Comment by durbanpoison** [comment]
That explains it... thanks!
